"""红线机制：免责声明、结论式表述拦截、引文防幻觉校验。

为什么单独成模块
----------------
本功能是"合规辅助筛查"，最容易出问题的地方不是识别率，而是**越界**：
一不小心就会输出"该网站允许爬取"这类实质上的法律结论。因此把三条硬约束
集中在这里，任何调用方都必须经过它：

1. :func:`disclaimer_text` / :func:`ensure_disclaimer`
   每份报告（含导出文件与界面）都必须携带固定免责声明。
2. :func:`sanitize_verdict`
   拦截并替换任何"结论式表述"（可以爬 / 不可以爬 / 合法 / 违法 …），
   统一改写为「需人工确认」。**只作用于工具生成的说明文字**，
   绝不改写原文引文——改写证据等于伪造证据。
3. :func:`quote_in_source`
   引文防幻觉：LLM 若返回引文，必须能在本地正文中精确匹配（空白归一化），
   否则丢弃该引文并计入 ``dropped_quotes``。
"""

from __future__ import annotations

import re

from core.compliance.models import REVIEW_NEEDED

DISCLAIMER_VERSION = "2026-09"

#: 固定免责声明（中英双语，中文在前）
DISCLAIMER = (
    "本报告由自动化工具基于目标网站的公开页面文本匹配生成，仅用于合规信息的辅助筛查，"
    "不构成法律意见，也不能替代律师或法务人员的专业判断。\n"
    "报告中所有条目均标记为“需人工确认”，只是待核对的线索，"
    "既不代表该网站“允许抓取”，也不代表“禁止抓取”，更不对行为的合法性作出判断。\n"
    "实际访问行为是否符合目标站点的服务条款、robots.txt 约定及相关法律法规，"
    "请务必自行咨询专业法律人士后决定。"
)
DISCLAIMER_EN = (
    "This report is generated by automated text matching over publicly accessible "
    "pages and is provided for compliance-screening assistance only. It is NOT legal "
    "advice and does not replace a qualified lawyer. Every item is flagged as "
    "\"needs human review\": it is a lead to verify, not a conclusion. Whether a "
    "crawl is permitted depends on the site's terms, robots.txt and applicable law "
    "— please consult a professional."
)

#: 统一替换标记
VERDICT_REPLACEMENT = f"【{REVIEW_NEEDED}】"

#: 结论式表述模式：命中即替换。
#: 设计原则——只匹配"下判断"的句式，不匹配描述性词汇，
#: 避免把"本条禁止爬取"这类原文叙述或"合规辅助筛查"这类模块名误伤
#: （且原文引文本来就不经过本函数）。
VERDICT_PATTERNS = (
    # 中文：允许/禁止类词组 + 采集动作（不含"是/属于"等中性系词，避免误伤描述性说明）
    re.compile(r"(?:可以|不可以|不能|能够|无法|允许|禁止)\s*(?:安全地?)?\s*"
               r"(?:爬取|抓取|采集|爬|抓|下载|访问)"),
    re.compile(r"(?:可以|不可以|能|不能)\s*(?:放心|安全|合法)?\s*(?:地)?\s*(?:爬取|抓取|采集|爬|抓)"),
    # 中文：合法性判定
    re.compile(r"(?:是|属于|构成|认定(?:为)?|判定(?:为)?|判断(?:为)?)\s*(?:合法|非法|违法|合规|违规|侵权)"),
    re.compile(r"(?:合法|非法|违法|合规|违规)性?\s*(?:的)?\s*(?:结论|判断|认定|风险)"),
    re.compile(r"(?:无|没有|不存在)\s*(?:任何)?\s*(?:法律|合规|侵权)?\s*风险"),
    re.compile(r"(?:触犯|违反|规避|绕过)\s*(?:法律|法规|刑法)"),
    re.compile(r"(?:建议|推荐|可以)\s*(?:直接)?\s*(?:开始)?\s*(?:抓取|爬取|采集)"),
    re.compile(r"(?:不)\s*(?:建议|推荐|应当|应该)\s*(?:抓取|爬取|采集)"),
    # 英文
    re.compile(r"(?i)\b(?:you|we|it)\s+(?:can|cannot|can't|may|may not|must not|"
               r"should|should not|are (?:not )?allowed to)\s+(?:crawl|scrape|harvest|collect)"),
    re.compile(r"(?i)\b(?:is|are)\s+(?:it\s+)?(?:legal|illegal|lawful|unlawful)\b"),
    re.compile(r"(?i)\b(?:legal|illegal|lawful|unlawful)\s+to\s+(?:crawl|scrape|harvest)"),
    re.compile(r"(?i)\b(?:no|zero)\s+(?:legal\s+)?risk\b"),
    re.compile(r"(?i)\bit\s+is\s+(?:safe|fine|ok(?:ay)?)\s+to\s+(?:crawl|scrape)"),
)


def disclaimer_text(with_english: bool = True) -> str:
    """返回固定免责声明文本（可选附带英文版）。"""
    return f"{DISCLAIMER}\n\n{DISCLAIMER_EN}" if with_english else DISCLAIMER


def sanitize_verdict(text: str) -> tuple[str, int]:
    """拦截并替换结论式表述。

    :return: (清洗后文本, 被替换的次数)
    """
    if not text:
        return text or "", 0
    total = 0
    result = str(text)
    for pattern in VERDICT_PATTERNS:
        result, count = pattern.subn(VERDICT_REPLACEMENT, result)
        total += count
    # 连续重复的替换标记合并，避免读起来像噪音
    if total:
        result = re.sub(r"(?:【需人工确认】){2,}", VERDICT_REPLACEMENT, result)
    return result, total


def sanitize_fields(data: dict, fields: tuple = ("llm_note", "llm_label",
                                                 "context_note")) -> tuple[dict, int]:
    """对字典中的指定文本字段批量执行结论式表述拦截。"""
    out = dict(data or {})
    total = 0
    for key in fields:
        value = out.get(key)
        if isinstance(value, str) and value:
            cleaned, count = sanitize_verdict(value)
            out[key] = cleaned
            total += count
    return out, total


def normalize_for_match(text: str) -> str:
    """归一化文本用于引文比对：统一大小写、全角空格与各类空白。"""
    if not text:
        return ""
    cleaned = str(text).replace("\u3000", " ").replace("\xa0", " ")
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned.strip().lower()


def quote_in_source(quote: str, source: str) -> bool:
    """校验引文是否真实存在于源文本中（空白归一化后的子串匹配）。

    LLM 返回的引文若不能通过本校验，说明存在编造/改写，调用方必须丢弃。
    """
    normalized_quote = normalize_for_match(quote)
    if not normalized_quote:
        return False
    # 容忍模型省略中间内容：按省略号切段，要求每段都能在原文本中找到
    segments = [seg for seg in re.split(r"(?:\.\.\.|…)+", normalized_quote)
                if seg.strip()]
    if not segments:
        return False
    haystack = normalize_for_match(source)
    return all(seg in haystack for seg in segments)


def ensure_disclaimer(report) -> bool:
    """确保报告带有免责声明与全部必需的"人工复核"标记。

    兼容 :class:`~core.compliance.models.ComplianceReport` 对象与字典。

    :return: True 表示报告合规（已补齐免责声明）
    """
    text = disclaimer_text()
    if isinstance(report, dict):
        report["disclaimer"] = text
        report["disclaimer_version"] = DISCLAIMER_VERSION
        for hit in report.get("findings") or []:
            hit["needs_human_review"] = True
        return True
    report.disclaimer = text
    report.disclaimer_version = DISCLAIMER_VERSION
    for hit in getattr(report, "findings", None) or []:
        hit.needs_human_review = True
    return True


__all__ = [
    "DISCLAIMER", "DISCLAIMER_EN", "DISCLAIMER_VERSION", "VERDICT_REPLACEMENT",
    "VERDICT_PATTERNS", "disclaimer_text", "sanitize_verdict", "sanitize_fields",
    "normalize_for_match", "quote_in_source", "ensure_disclaimer",
]
